### ISSUE TITLE
Transaction simulation failed issue

### ISSUE THREAD

**Issue by panchuprodhan** [gagliardetto/metaplex-go#6]
**panic: (*jsonrpc.RPCError)(0xc0003840f0)({
 Code: (int) -32002,
 Message: (string) (len=89) "Transaction simulation failed: Error processing Instruction 2: custom program error: 0x65",
 Data: (map[string]interface {}) (len=4) {
  (string) (len=8) "accounts": (interface {}) <nil>,
  (string) (len=3) "err": (map[string]interface {}) (len=1) {
   (string) (len=16) "InstructionError": ([]interface {}) (len=2 cap=2) {
    (json.Number) (len=1) "2",
    (map[string]interface {}) (len=1) {
     (string) (len=6) "Custom": (json.Number) (len=3) "101"
    }
   }
  },
  (string) (len=4) "logs": ([]interface {}) (len=8 cap=8) {
   (string) (len=51) "Program 11111111111111111111111111111111 invoke [1]",
   (string) (len=48) "Program 11111111111111111111111111111111 success",
   (string) (len=51) "Program 11111111111111111111111111111111 invoke [1]",
   (string) (len=48) "Program 11111111111111111111111111111111 success",
   (string) (len=63) "Program 7oF9LvweSVTeKSMPYbY45aPcwha1QWrfM6rjW961qLkU invoke [1]",
   (string) (len=39) "Program log: Custom program error: 0x65",
   (string) (len=90) "Program 7oF9LvweSVTeKSMPYbY45aPcwha1QWrfM6rjW961qLkU consumed 2531 of 200000 compute units",
   (string) (len=87) "Program 7oF9LvweSVTeKSMPYbY45aPcwha1QWrfM6rjW961qLkU failed: custom program error: 0x65"
  },
  (string) (len=13) "unitsConsumed": (json.Number) (len=1) "0"
 }
})

goroutine 1 [running]:
main.sendTx(0xc00018d860, 0xc000100730, 0x93e51c, 0x1c, 0xc0002ea180, 0x6, 0x6, 0xc000326050, 0x3, 0x3)
        /mnt/d/Nibir work/solana_nft/metaplex-go/examples/candy/main.go:485 +0x885
main.main()
        /mnt/d/Nibir work/solana_nft/metaplex-go/examples/candy/main.go:207 +0x1ce5
exit status 2**

`go run .`
from the examples/candy folder

Getting the error marked in bold; I'm having 1000 SOL's. Can you please help me out here.

**Comment by gagliardetto** [comment]
Hi

Currently I have only a client for the CandyMachineV1, which is deprecated (cannot create new V1 candy machines).

From the log you posted, the relevant part is `(string) (len=39) "Program log: Custom program error: 0x65",`

The hex `0x65` corresponds to 101 in decimal. This is in the range of anchor errors.

If you search 101 in the anchor repo ([like this](https://github.com/project-serum/anchor/search?q=101)), you'll find: https://github.com/project-serum/anchor/blob/b3720a0b84c4874be3a492950efbf02f717d2ace/lang/src/error.rs#L20-L22

That means the instruction is not recognized (or something like that).

**Comment by panchuprodhan** [comment]
Hi, 

Thanks for the previous help. It helped. But recently deployed the CandyMachineV1.

Getting this error at the current time `(string) (len=39) "Program log: Custom program error: 0xa7"`
